### ISSUE TITLE
Semantic error TS1149 in newly setup project

### ISSUE THREAD

**Issue by Tommycore** [ghost-fvtt/foundry-factory#39] opened 2021-10-31 12:05 UTC
I've just setup a new project. As soon as I try to build (either by `npm run build` or `npm run build:watch`), I get the following error on the build process. I know that happened before in another project and I got that solved. Just can't figure out for the life of me how I did that. Tried anything I found here: https://stackoverflow.com/questions/51197940/file-name-differs-from-already-included-file-name-only-in-casing-on-relative-p but to no avail.

If it matters: I'm using Win10 x64.

```
Error: E:/Repos/tommycore/world-map/src/module/world-map.ts(15,34): semantic error TS1149: File name 'E:/Repos/tommycore/world-map/src/module/preloadTemplates.ts' differs from 
already included file name 'E:/repos/tommycore/world-map/src/module/preloadTemplates.ts' only in casing.
  The file is in the program because:
    Root file specified for compilation
    Imported via './preloadTemplates' from file 'E:/Repos/tommycore/world-map/src/module/world-map.ts'
    at error (E:\repos\tommycore\world-map\node_modules\rollup\dist\shared\rollup.js:158:30)
    at throwPluginError (E:\repos\tommycore\world-map\node_modules\rollup\dist\shared\rollup.js:21741:12)
    at Object.error (E:\repos\tommycore\world-map\node_modules\rollup\dist\shared\rollup.js:22415:20)
    at Object.error (E:\repos\tommycore\world-map\node_modules\rollup\dist\shared\rollup.js:21917:38)
    at RollupContext.error (E:\repos\tommycore\world-map\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:17241:30)
    at E:\repos\tommycore\world-map\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:25064:23
    at arrayEach (E:\repos\tommycore\world-map\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:549:11)
    at Function.forEach (E:\repos\tommycore\world-map\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:9401:14)
    at printDiagnostics (E:\repos\tommycore\world-map\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:25037:12)
    at Object.transform (E:\repos\tommycore\world-map\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:30131:17)
```

**Comment by ghost91-** [comment] 2021-10-31 15:20
Thanks for the report! I'll take a look and address the issue as soon as possible, probably tomorrow or the day after. Sorry for the inconvenience.

**Comment by Tommycore** [comment] 2021-11-02 11:38
Much appreciated. Feel free to hit me up on Discord for further information or testing, if you like.

**Comment by ghost91-** [comment] 2021-11-05 17:13
I'm not able to reproduce the issue you were having with foundry-factory. To me, it looks like it's an issue with Windows + case sensitivity. But for me, it doesn't happen. I set up a module on my windows 10, 64bit machine, in the exact same path as you did (well, in C:\ instead of E:\ but that shouldn't matter). For me, everything works fine.

I don't really know what I can do about this...

**Comment by ghost91-** [comment] 2022-01-20 11:50
Closing this as it doesn't seem to be related specifically to foundry-factory and it's not possible to reproduce it reliably.

**Closed by ghost91-** 2022-01-20 11:50 UTC
Labels: bug, help wanted
